### ISSUE TITLE
Scanning a directory leads to an error

### ISSUE THREAD

**Issue by cbitterfield** [xenomachina/dvdrip#12]
Platform: OSX 12.4
HandbrakeCLI: 
 `HandBrakeCLI --version
[23:38:09] Compile-time hardening features are enabled
[23:38:09] hb_init: starting libhb thread
[23:38:09] thread 7000042f1000 started ("libhb")
HandBrake 1.5.1`
VLC: Not installed for this test.

DIRECTORY=../VOBS

COMMAND:  dvdrip --scan -i ./VOBs/

Results:

dvdrip --scan -i ./VOBs/
Reading from './VOBs/'
Traceback (most recent call last):
  File "/usr/local/src/dvdrip/dvdrip.py", line 684, in <module>
    main()
  File "/usr/local/src/dvdrip/dvdrip.py", line 648, in main
    titles = tuple(dvd.ScanTitles(title_numbers, args.verbose))
  File "/usr/local/src/dvdrip/dvdrip.py", line 341, in ScanTitles
    raw_scan = tuple(self.ScanTitle(first))
  File "/usr/local/src/dvdrip/dvdrip.py", line 325, in ScanTitle
    for line in check_err([
  File "/usr/local/src/dvdrip/dvdrip.py", line 151, in check_err
    raise subprocess.CalledProcessError(retcode, cmd, output=stderr)
subprocess.CalledProcessError: Command '['HandBrakeCLI', '--scan', '--title', '1', '-i', './VOBs/']' returned non-zero exit status 2.

**Comment by xenomachina** [comment]
What happens if you enter the following HandBrakeCLI command in the terminal?

···
HandBrakeCLI --scan' -title 1 -I ./VOBs/
···

**Comment by dmike23** [comment]
How do I call my DVD drive? 

Like this?

"dvdrip>python dvdrip.py --scan E: "   ????

I get: 'dvdrip' is not recognized as an internal or external command,
operable program or batch file.

**Comment by xenomachina** [comment]
@dmike23 Where did you get that command? "dvdrip>" looks like a prompt, not part of the command, but based on the error it sounds like you typed it in.
