### ISSUE TITLE
AssertionError: UNMATCHED

### ISSUE THREAD

**Issue by Jab2870** [xenomachina/dvdrip#4]
Hi,
I am having the following problem when trying to scan a DVD. Please can you assist?

```
$ dvdrip -i /mnt/cd  --scan
Reading from '/mnt/cd'
Disc claims to have 17 titles.
warning: Cannot scan title 4.
warning: Cannot scan title 8.
warning: Cannot scan title 9.
warning: Cannot scan title 10.
warning: Cannot scan title 11.
warning: Cannot scan title 12.
warning: Cannot scan title 15.
warning: Cannot scan title 16.
warning: Cannot scan title 17.
Title   1/  8: 01:42:49  720×576  16:9   25 fps
  audio   1: English (5.1ch)  [48000Hz, 384000bps]
warning: Cannot parse audio track fields '(AC3) (Visually Impaired) (2.0 ch) (iso639-2: eng)'
  audio   3: العربية (5.1ch)  [48000Hz, 384000bps]
  audio   4: Türkçe (5.1ch)  [48000Hz, 384000bps]
Traceback (most recent call last):
  File "/home/jonathan/.bin/dvdrip", line 689, in <module>
    main()
  File "/home/jonathan/.bin/dvdrip", line 656, in main
    DisplayScan(titles)
  File "/home/jonathan/.bin/dvdrip", line 568, in DisplayScan
    for sub in ParseSubtitleTracks(info['subtitle tracks']):
  File "/home/jonathan/.bin/dvdrip", line 537, in ParseSubtitleTracks
    assert m, 'UNMATCHED %r' % info
AssertionError: UNMATCHED 'English Closed Caption (Wide Screen) [VOBSUB]'

```

**Comment by wamcvey** [comment]
I'm having similar issues:
```
Disc claims to have 5 titles.
./dvdrip.py:472: DeprecationWarning: fractions.gcd() is deprecated. Use math.gcd() instead.
  d = gcd(w, h)
Title   1/  5: 00:43:26  720×480  4:3  29.97 fps
  audio   1: English (5.1ch)  [48000Hz, 384000bps]
  audio   2: Deutsch (5.1ch)  [48000Hz, 384000bps]
  audio   3: 日本語 (5.1ch)  [48000Hz, 384000bps]
  audio   4: 中文 (5.1ch)  [48000Hz, 384000bps]
Traceback (most recent call last):
  File "./dvdrip.py", line 687, in <module>
    main()
  File "./dvdrip.py", line 654, in main
    DisplayScan(titles)
  File "./dvdrip.py", line 566, in DisplayScan
    for sub in ParseSubtitleTracks(info['subtitle tracks']):
  File "./dvdrip.py", line 535, in ParseSubtitleTracks
    assert m, 'UNMATCHED %r' % info
AssertionError: UNMATCHED 'English (4:3) [VOBSUB]'
```
