### ISSUE TITLE
AssertionError: Can't find TITLE_COUNT_REGEX in scan

### ISSUE THREAD

**Issue by j4k3** [xenomachina/dvdrip#5]
Can't give much more info than this, newest version of handbrake is installed, while starting a scan the script exits with this error: 
```
Reading from '/Volumes/KING_KONG_EXTENDED_EDITION'
Traceback (most recent call last):
  File "./dvdrip.py", line 687, in <module>
    main()
  File "./dvdrip.py", line 651, in main
    titles = tuple(dvd.ScanTitles(title_numbers, args.verbose))
  File "./dvdrip.py", line 339, in ScanTitles
    title_count = FindTitleCount(raw_scan, verbose)
  File "./dvdrip.py", line 171, in FindTitleCount
    raise AssertionError("Can't find TITLE_COUNT_REGEX in scan")
AssertionError: Can't find TITLE_COUNT_REGEX in scan
```

**Comment by xenomachina** [comment]
I've pushed a change that should make this error less likely to happen.
