### ISSUE TITLE
Don't understand input path on Windows machine

### ISSUE THREAD

**Issue by AlexZibin** [xenomachina/dvdrip#9]
Hi, 
Thank you for this program.

However, it's not working on Windows. 
It can't understand the input path; the errors are as follows:
`dvdrip.py --scan -i d:
 Reading from 'd:'
 Traceback (most recent call last):
  File "C:\Users\Alex\Documents\Python\dvdrip\dvdrip.py", line 684, in <module>
    main()
  File "C:\Users\Alex\Documents\Python\dvdrip\dvdrip.py", line 648, in main
    titles = tuple(dvd.ScanTitles(title_numbers, args.verbose))
  File "C:\Users\Alex\Documents\Python\dvdrip\dvdrip.py", line 341, in ScanTitles
    raw_scan = tuple(self.ScanTitle(first))
  File "C:\Users\Alex\Documents\Python\dvdrip\dvdrip.py", line 325, in ScanTitle
    for line in check_err([
  File "C:\Users\Alex\Documents\Python\dvdrip\dvdrip.py", line 144, in check_err
    process = subprocess.Popen(stderr=subprocess.PIPE, *popenargs, **kwargs)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]`

I also used dozens of other input paths instead of 'd:':  **_d:\, d:/, "d:\", D:\VIDEO_TS_** but this doesn't change the error message.
Even **_dvdrip.py --scan -i c:_** leads to the same error.

Please help.

**Comment by xenomachina** [comment]
Hi @AlexZibin,

Sorry for the terrible error message. Do you have HandBrakeCLI installed, and in your path? I think it's unable to execute it.
